CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: CI with dynamic parallel matrix
 
 on:
   workflow_dispatch:
@@ -12,81 +12,170 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  LITERATE_PROC: '4'
+  CACHE_NUM: '1'
+  LITERATE_PROC: '2'
   JULIA_CI: 'true'
-  # JULIA_CPU_TARGET: 'generic;icelake-server,clone_all;znver3,clone_all'
-  JULIA_NUM_THREADS: '1'
+  JULIA_CPU_TARGET: 'generic;icelake-server,clone_all;znver3,clone_all'
+  JULIA_NUM_THREADS: '2'
   OPENBLAS_NUM_THREADS: '1'
   NBCACHE: '.cache'
+  PY_VER: '3.14'
+  JULIA_CONDAPKG_OFFLINE: true
+  JULIA_CONDAPKG_BACKEND: 'Null'
 
 jobs:
-  CI:
-    runs-on: ubuntu-24.04-arm
-    permissions:
-      actions: write
-      contents: read
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      env: ${{ steps.hash.outputs.env }}
+      jl: ${{ steps.hash.outputs.jl }}
+      ver: ${{ steps.julia-version.outputs.resolved }}
     steps:
     - name: Checkout repository
       uses: actions/checkout@v6
-    - name: Read Julia version
-      uses: julia-actions/julia-version@main
-      id: julia-version
+    - name: Setup uv
+      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
       with:
-        versions: manifest
-    - name: Get hashes
+        python-version: ${{ env.PY_VER }}
+        activate-environment: true
+    - name: Install Python deps
+      run: uv pip install -r requirements.txt
+    - name: Add python venv to path
+      run: |
+          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
+          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
+    - name: Read Julia version
+      id: julia-version
+      run: python -c 'import tomllib; from pathlib import Path; print("resolved=", tomllib.loads(Path("Manifest.toml").read_text())["julia_version"], sep="")' >> "$GITHUB_OUTPUT"
+    - name: Get environment hashes
       id: hash
       run: |
-        echo "value=${{ hashFiles('Project.toml', 'Manifest.toml', 'Startup/**') }}" >> "$GITHUB_OUTPUT"
-        echo "nb=${{ hashFiles('docs/**/*.jl', 'docs/**/*.ipynb') }}" >> "$GITHUB_OUTPUT"
-    - name: Cache executed notebooks
-      uses: actions/cache@v5
-      id: cache-nb
-      with:
-        path: |
-          ${{ env.NBCACHE }}/**/*.ipynb
-          ${{ env.NBCACHE }}/**/*.sha
-        key: notebook-${{ steps.hash.outputs.value }}-${{ steps.hash.outputs.nb }}
-        restore-keys: |
-          notebook-${{ steps.hash.outputs.value }}-
+        echo "jl=${{ runner.os }}-${{ runner.arch }}-julia-${{ steps.julia-version.outputs.resolved }}" >> "$GITHUB_OUTPUT"
+        echo "env=${{ env.CACHE_NUM }}-${{ hashFiles('Project.toml', 'Manifest.toml', 'Startup/**') }}" >> "$GITHUB_OUTPUT"
     - name: Setup Julia
       uses: julia-actions/setup-julia@v3
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' }}
       with:
         version: ${{ steps.julia-version.outputs.resolved }}
     - name: Cache Julia packages
-      uses: julia-actions/cache@v3
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' && runner.environment == 'github-hosted' }}
+      uses: actions/cache@v5
       id: cache-julia
+      with:
+        path: ~/.julia
+        key: ${{ steps.hash.outputs.jl }}-${{ steps.hash.outputs.env }}
+        restore-keys: |
+          ${{ steps.hash.outputs.jl }}-
     - name: Install Julia packages
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' && (runner.environment == 'self-hosted' || steps.cache-julia.outputs.cache-hit != 'true') }}
       shell: julia --color=yes --project=@. {0}
       run: using Pkg; Pkg.instantiate()
-    - name: Run notebooks
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' }}
-      run: julia --project=@. --color=yes -p ${{ env.LITERATE_PROC }} .github/ci.jl
-    - name: Copy back built notebooks
-      run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
-    - name: Setup NodeJS
-      uses: actions/setup-node@v6
-      with:
-        node-version: 'lts/*'
-    - name: Build website
-      env:
-        BASE_URL: /${{ github.event.repository.name }}
-      working-directory: docs
-      run: |
-        npm install -g "jupyter-book"
-        jupyter-book build --html
-    - name: Upload pages artifact
-      if: ${{ github.ref == 'refs/heads/main' }}
-      uses: actions/upload-pages-artifact@v5
-      with:
-        path: 'docs/_build/html'
+    - name: List notebooks as a JSON array
+      id: set-matrix
+      run: echo "matrix=$(python -c 'import glob, json; print(json.dumps(glob.glob("**/*.ipynb", root_dir="docs", recursive=True) + glob.glob("**/*.jl", root_dir="docs", recursive=True)))')" >> "$GITHUB_OUTPUT"
+
+  execute:
+    needs: setup
+    strategy:
+      max-parallel: 10
+      fail-fast: false
+      matrix:
+        notebook: ${{ fromJSON(needs.setup.outputs.matrix) }}
+    runs-on: ubuntu-latest
+    env:
+      NB: docs/${{ matrix.notebook }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Cache notebook
+        uses: actions/cache@v5
+        id: nb-cache
+        with:
+          path: ${{ env.NBCACHE }}
+          key: notebook-${{ needs.setup.outputs.env }}-${{ hashFiles(env.NB) }}
+      - name: Setup uv
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
+        with:
+          python-version: ${{ env.PY_VER }}
+          activate-environment: true
+      - name: Setup Julia
+        uses: julia-actions/setup-julia@v3
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        with:
+          version: ${{ needs.setup.outputs.ver }}
+      - name: Restore Julia packages
+        uses: actions/cache/restore@v5
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        id: cache-julia
+        with:
+          path: ~/.julia
+          key: ${{ needs.setup.outputs.jl }}
+      - name: Execute notebook
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        run: |
+          uv pip install -r requirements.txt
+          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
+          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
+          julia --project=@. .github/ci.jl
+      - name: Convert artifact Name
+        id: art
+        run: echo "name=$(echo ${{ env.NB }} | sed 's/\//-/g')" >> "$GITHUB_OUTPUT"
+      - name: Upload Notebook
+        uses: actions/upload-artifact@v7
+        with:
+          name: notebook-${{ steps.art.outputs.name }}-${{ needs.setup.outputs.env }}-${{ hashFiles(env.NB) }}
+          path: ${{ env.NBCACHE }}
+          include-hidden-files: true
+
+  render:
+    needs: execute
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Download notebooks
+        uses: actions/download-artifact@v8
+        with:
+          path: ${{ env.NBCACHE }}/
+          pattern: notebook-*
+          merge-multiple: true
+      - name: Copy back built notebooks
+        run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
+      - name: Setup NodeJS
+        uses: actions/setup-node@v6
+        with:
+          node-version: 'lts/*'
+      - name: Build website
+        env:
+          BASE_URL: /${{ github.event.repository.name }}
+        working-directory: docs
+        run: |
+          npm install -g "jupyter-book"
+          jupyter-book build --html
+      - name: Upload pages artifact
+        if: ${{ github.ref == 'refs/heads/main' }}
+        uses: actions/upload-pages-artifact@v5
+        with:
+          path: 'docs/_build/html'
+
+  # CI conclusion for GitHub status check
+  CI:
+    needs: render
+    if: always()
+    runs-on: ubuntu-slim
+    steps:
+      - run: |
+          if [[ ${{ needs.render.result }} == "success" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
 
   # Deployment job
   deploy:
-    name: Deploy to GitHub pages and Notebook branch
-    needs: CI
+    name: Deploy to GitHub pages
+    needs: render
     if: ${{ github.ref == 'refs/heads/main' }}
     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
